version: '3.5'

services:
  elasticsearch:
    build:
      context: elk/elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: elasticsearch
    volumes:
      - type: bind
        source: ./elk/elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true 
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    networks:
      - elk

  logstash:
    build:
      context: elk/logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: logstash
    volumes:
      - type: bind
        source: ./elk/logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./elk/logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true 
    ports:
      - "5044:5044"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch
      - redis

  kibana:
    build:
      context: elk/kibana/
      args:
        ELK_VERSION: $ELK_VERSION      
    container_name: kibana
    volumes:
      - type: bind
        source: ./elk/kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true 
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
  
  redis:    
    build:
      context: elk/redis/
      args:
        REDIS_VERSION: $REDIS_VERSION
    container_name: redis
    ports: 
      - "6379:6379"  
    environment:
    # In dev only!
    - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - elk

  filebeat:
    build:
      context: elk/filebeat/
      args:
        ELK_VERSION: $ELK_VERSION      
    container_name: filebeat
    volumes:
      - type: bind
        source: ./elk/filebeat/config/filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
        read_only: true 
      - ./elk/filebeat/log:/app/log:ro
    networks:
      - elk
    depends_on:
      - redis

networks:
  elk:
    driver: bridge